# Generated by Django 3.2.7 on 2021-12-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('alert', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'naga_camera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(default='', max_length=10)),
                ('imgUrl', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'naga_event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgUrl', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'naga_image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('alert', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'naga_shop',
                'managed': False,
            },
        ),
    ]
