# Generated by Django 3.2.7 on 2021-11-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(blank=True, null=True, upload_to='snapshot/%Y/%m/%d/%H/%M', verbose_name='스냅샷')),
                ('filename', models.CharField(max_length=64, null=True, verbose_name='파일명')),
                ('content_type', models.CharField(max_length=128, null=True, verbose_name='Mimetype')),
                ('size', models.IntegerField(verbose_name='파일크기')),
                ('reg_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일')),
            ],
            options={
                'ordering': ('-reg_date',),
            },
        ),
    ]
