# Generated by Django 3.2.7 on 2021-11-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='video/%Y/%m/%d/%H', verbose_name='녹화 파일')),
                ('filename', models.CharField(max_length=64, null=True, verbose_name='파일명')),
                ('content_type', models.CharField(max_length=128, null=True, verbose_name='Mimetype')),
                ('size', models.IntegerField(verbose_name='파일크기')),
                ('reg_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일')),
            ],
            options={
                'ordering': ('-reg_date',),
            },
        ),
    ]
